version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./build/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  web:
    build: ./build/apache
    tty: true
    container_name: apache-php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    links:
      - mysql